title: UNO: Chaos edition
description: Markdown documentation for an UNO ruleset I created with the goal of creating as much chaos as possible with a standard uno flip card deck
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
