remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: UNO: Chaos edition
description: Markdown documentation for an UNO ruleset I created with the goal of creating as much chaos as possible with a standard uno flip card deck
show_downloads: true
